EXECUTE BLOCK AS BEGIN
  IF (EXISTS(SELECT 1 FROM rdb$generators WHERE rdb$generator_name = 'SEQ_CHILD_ID')) THEN
    EXECUTE STATEMENT 'DROP SEQUENCE SEQ_CHILD_ID;';
END!!

EXECUTE BLOCK AS BEGIN
   IF (EXISTS(SELECT 1 FROM rdb$generators WHERE rdb$generator_name = 'SEQ_PARENT_ID')) THEN
    EXECUTE STATEMENT 'DROP SEQUENCE SEQ_PARENT_ID;';
END!!

EXECUTE BLOCK AS BEGIN
  IF (EXISTS(select 1 FROM rdb$relations WHERE rdb$relation_name = 'CHILD_ENTITY')) THEN
    EXECUTE STATEMENT 'DROP TABLE CHILD_ENTITY;';
END!!

EXECUTE BLOCK AS BEGIN
  IF (EXISTS(SELECT 1 FROM rdb$relations WHERE rdb$relation_name = 'PARENT_ENTITY')) THEN
    EXECUTE STATEMENT 'DROP TABLE PARENT_ENTITY;';
END!!

CREATE TABLE PARENT_ENTITY (
  PARENT_ID BIGINT NOT NULL,
  PRIMARY KEY (PARENT_ID)
)!!

CREATE TABLE CHILD_ENTITY (
  CHILD_ID BIGINT NOT NULL,
  PARENT_ID BIGINT NOT NULL,
  PRIMARY KEY (CHILD_ID),
  FOREIGN KEY (PARENT_ID) REFERENCES PARENT_ENTITY (PARENT_ID)
)!!

CREATE SEQUENCE SEQ_PARENT_ID!!

CREATE SEQUENCE SEQ_CHILD_ID!!

