DROP SEQUENCE IF EXISTS SEQ_CHILD_ID;
DROP SEQUENCE IF EXISTS SEQ_PARENT_ID;

DROP TABLE IF EXISTS CHILD_ENTITY;
DROP TABLE IF EXISTS PARENT_ENTITY;

CREATE TABLE PARENT_ENTITY (
  PARENT_ID BIGINT NOT NULL,
  PRIMARY KEY (PARENT_ID)
);

CREATE TABLE CHILD_ENTITY (
  CHILD_ID BIGINT NOT NULL,
  PARENT_ID BIGINT NOT NULL,
  PRIMARY KEY (CHILD_ID),
  FOREIGN KEY (PARENT_ID) REFERENCES PARENT_ENTITY (PARENT_ID)
);

CREATE SEQUENCE SEQ_PARENT_ID
CACHE 50;

CREATE SEQUENCE SEQ_CHILD_ID
CACHE 50;

