
DECLARE
  l_tsequence_count NUMBER(1);
BEGIN

  SELECT COUNT(*)
    INTO l_tsequence_count
    FROM user_sequences
   WHERE sequence_name = 'SEQ_CHILD_ID';

  IF l_tsequence_count > 0 THEN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CHILD_ID';
  END IF;
END;!!

DECLARE
  l_tsequence_count NUMBER(1);
BEGIN

  SELECT COUNT(*)
    INTO l_tsequence_count
    FROM user_sequences
   WHERE sequence_name = 'SEQ_PARENT_ID';

  IF l_tsequence_count > 0 THEN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PARENT_ID';
  END IF;
END;!!

DECLARE
  l_table_count NUMBER(1);
BEGIN

  SELECT COUNT(*)
    INTO l_table_count
    FROM user_tables
   WHERE table_name = 'CHILD_ENTITY';

  IF l_table_count > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE CHILD_ENTITY';
  END IF;
END;!!

DECLARE
  l_table_count NUMBER(1);
BEGIN

  SELECT COUNT(*)
    INTO l_table_count
    FROM user_tables
   WHERE table_name = 'PARENT_ENTITY';

  IF l_table_count > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE PARENT_ENTITY';
  END IF;
END;!!

CREATE TABLE PARENT_ENTITY (
  PARENT_ID NUMBER(18) NOT NULL,
  CONSTRAINT PARENT_ID_PK
  PRIMARY KEY (PARENT_ID)
)!!

CREATE TABLE CHILD_ENTITY (
  CHILD_ID NUMBER(18) NOT NULL,
  PARENT_ID NUMBER(18) NOT NULL,
  CONSTRAINT CHILD_ID_PK
  PRIMARY KEY (CHILD_ID),
  CONSTRAINT PARENT_ID_FK
  FOREIGN KEY (PARENT_ID) REFERENCES PARENT_ENTITY (PARENT_ID)
)!!

CREATE SEQUENCE SEQ_PARENT_ID
START WITH 1
MINVALUE 1
CACHE 50!!

CREATE SEQUENCE SEQ_CHILD_ID
START WITH 1
MINVALUE 1
CACHE 50!!

