-- sequence does not have to be dropped because it's owned by the column
DROP TABLE IF EXISTS CHILD_ENTITY;
DROP TABLE IF EXISTS PARENT_ENTITY;

CREATE TABLE PARENT_ENTITY (
  PARENT_ID BIGINT NOT NULL,
  PRIMARY KEY (PARENT_ID)
);

CREATE TABLE CHILD_ENTITY (
  CHILD_ID BIGINT NOT NULL,
  PARENT_ID BIGINT NOT NULL,
  PRIMARY KEY (CHILD_ID),
  FOREIGN KEY (PARENT_ID) REFERENCES PARENT_ENTITY (PARENT_ID)
);

CREATE SEQUENCE SEQ_PARENT_ID
CACHE 50
OWNED BY PARENT_ENTITY.PARENT_ID;

CREATE SEQUENCE SEQ_CHILD_ID
CACHE 50
OWNED BY CHILD_ENTITY.CHILD_ID;

