name: Java CI with Maven

on:
  push:
    branches: [ "v3" ]
  pull_request:
    branches: [ "v3" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Maven toolchain build
    steps:
    - uses: actions/checkout@v7
    - name: Set up JDKs
      uses: actions/setup-java@v6
      with:
        distribution: 'zulu'
        java-version: 17
        cache: maven
    - name: Maven verify
      run: mvn --batch-mode --no-transfer-progress verify